---
Name: paymentdpsroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    dpspxpaypayment//$Action/$ID: Sunnysideup\PaymentDps\Control\DpsPxPayPaymentHandler
    dpspxpaystoredpayment//$Action/$ID: Sunnysideup\PaymentDps\Control\DpsPxPayStoredPaymentHandler
