---
Name: paymentdpsroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    dpspxpaypayment//$Action/$ID: Sunnysideup\PaymentDps\Control\DpsPxPayPayment_Handler
    dpspxpaystoredpayment//$Action/$ID: Sunnysideup\PaymentDps\Control\DpsPxPayStoredPayment_Handler
